spring:
  jpa:
    hibernate:
      ddlAuto: validate
    showSql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/eshop
    username: eshopAdmin
    password: 358000
  flyway:
    baselineOnMigrate: true
    out-of-order: true
server:
  port: 35664
